# Generated by Django 4.1 on 2024-02-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="del_flag",
            field=models.SmallIntegerField(
                default=1, max_length=1, verbose_name="删除标志"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="del_flag",
            field=models.SmallIntegerField(
                default=1, max_length=1, verbose_name="删除标志"
            ),
        ),
    ]
