# Generated by Django 4.1 on 2024-02-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_alter_userinfo_create_time_alter_userinfo_depart"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrettyNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="手机号")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[
                            (1, "黑铁级"),
                            (4, "黄金级"),
                            (3, "白银级"),
                            (5, "钻石级"),
                            (2, "青铜级"),
                        ],
                        default=1,
                        verbose_name="级别",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "已占用"), (0, "未占用")], default=0, verbose_name="状态"
                    ),
                ),
                ("del_flag", models.IntegerField(default=1, verbose_name="删除标志")),
            ],
        ),
    ]
