# Generated by Django 4.1 on 2024-02-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_prettynum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="用户名")),
                ("del_flag", models.SmallIntegerField(default=1, verbose_name="删除标志")),
            ],
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(5, "钻石级"), (4, "黄金级"), (3, "白银级"), (1, "黑铁级"), (2, "青铜级")],
                default=1,
                verbose_name="级别",
            ),
        ),
    ]
