# Generated by Django 4.1 on 2024-02-06 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_admin_alter_prettynum_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=64, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="admin",
            name="username",
            field=models.CharField(max_length=32, verbose_name="管理员姓名"),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(2, "青铜级"), (5, "钻石级"), (1, "黑铁级"), (4, "黄金级"), (3, "白银级")],
                default=1,
                verbose_name="级别",
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="status",
            field=models.IntegerField(
                choices=[(0, "未占用"), (1, "已占用")], default=0, verbose_name="状态"
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                ("detail", models.TextField(verbose_name="详细信息")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "紧急"), (3, "一般"), (2, "重要")],
                        default=3,
                        verbose_name="级别",
                    ),
                ),
                ("del_flag", models.SmallIntegerField(default=1, verbose_name="删除标志")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.admin",
                        verbose_name="负责人",
                    ),
                ),
            ],
        ),
    ]
