# Generated by Django 4.1 on 2024-02-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_alter_admin_password_alter_admin_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "黑铁级"), (4, "黄金级"), (5, "钻石级"), (3, "白银级"), (2, "青铜级")],
                default=1,
                verbose_name="级别",
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="status",
            field=models.IntegerField(
                choices=[(1, "已占用"), (0, "未占用")], default=0, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.SmallIntegerField(
                choices=[(3, "一般"), (2, "重要"), (1, "紧急")], default=3, verbose_name="级别"
            ),
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="订单号")),
                ("title", models.CharField(max_length=32, verbose_name="名称")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "已支付"), (0, "未支付")], default=0, verbose_name="状态"
                    ),
                ),
                ("del_flag", models.SmallIntegerField(default=1, verbose_name="删除标志")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.userinfo",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
