# Generated by Django 4.1 on 2024-02-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_alter_prettynum_level_alter_prettynum_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("img", models.CharField(max_length=256, verbose_name="文件路径")),
            ],
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "未支付"), (1, "已支付")], default=0, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(2, "青铜级"), (3, "白银级"), (5, "钻石级"), (1, "黑铁级"), (4, "黄金级")],
                default=1,
                verbose_name="级别",
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="status",
            field=models.IntegerField(
                choices=[(0, "未占用"), (1, "已占用")], default=0, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "紧急"), (2, "重要"), (3, "一般")], default=3, verbose_name="级别"
            ),
        ),
    ]
