# Generated by Django 4.1 on 2024-02-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0009_boss_alter_orders_status_alter_prettynum_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boss",
            name="img_real_path",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="实际文件路径"
            ),
        ),
        migrations.AlterField(
            model_name="boss",
            name="img",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Django文件路径"
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "黑铁级"), (4, "黄金级"), (2, "青铜级"), (3, "白银级"), (5, "钻石级")],
                default=1,
                verbose_name="级别",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.SmallIntegerField(
                choices=[(3, "一般"), (2, "重要"), (1, "紧急")], default=3, verbose_name="级别"
            ),
        ),
    ]
