# Generated by Django 4.1 on 2024-02-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0010_boss_img_real_path_alter_boss_img_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名称")),
                ("count", models.IntegerField(verbose_name="人口")),
                (
                    "img",
                    models.FileField(
                        max_length=256, upload_to="city/", verbose_name="logo"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(2, "青铜级"), (4, "黄金级"), (1, "黑铁级"), (3, "白银级"), (5, "钻石级")],
                default=1,
                verbose_name="级别",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.SmallIntegerField(
                choices=[(2, "重要"), (3, "一般"), (1, "紧急")], default=3, verbose_name="级别"
            ),
        ),
    ]
